#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TokenKind {
    Identifier,
    Type,
    Int,
    Double,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    Plus,
    Minus,
    Multiply,
    Divide,
    Assign,
    Equal,
    Greater,
    GreaterOrEqual,
    Less,
    LessOrEqual,
    Colon,
    Comma,
    NewLine,
    Function,
    Return,
    True,
    False,
    EOF,
}

impl ToString for TokenKind {
    fn to_string(&self) -> String {
        match self {
            TokenKind::Identifier => "identifier".into(),
            TokenKind::Type => "type".into(),
            TokenKind::Int => "int".into(),
            TokenKind::Double => "double".into(),
            TokenKind::OpenParen => "'('".into(),
            TokenKind::CloseParen => "')'".into(),
            TokenKind::OpenBrace => "'{'".into(),
            TokenKind::CloseBrace => "'}'".into(),
            TokenKind::Plus => "'+'".into(),
            TokenKind::Minus => "'-'".into(),
            TokenKind::Multiply => "'*'".into(),
            TokenKind::Divide => "'/'".into(),
            TokenKind::Assign => "'='".into(),
            TokenKind::Equal => "'=='".into(),
            TokenKind::Greater => "'>'".into(),
            TokenKind::GreaterOrEqual => "'>='".into(),
            TokenKind::Less => "'<'".into(),
            TokenKind::LessOrEqual => "'<='".into(),
            TokenKind::Colon => "':'".into(),
            TokenKind::Comma => "','".into(),
            TokenKind::NewLine => "newline".into(),
            TokenKind::Function => "'fn'".into(),
            TokenKind::Return => "'return'".into(),
            TokenKind::True => "true".into(),
            TokenKind::False => "false".into(),
            TokenKind::EOF => "eof".into(),
        }
    }
}
